"""
Streamlit dashboard application for Groundwater Recharge Insight Dashboard.
"""

import logging
import os
from datetime import datetime, timedelta

import streamlit as st
import pandas as pd
from dotenv import load_dotenv

# Load .env before anything reads os.environ (notably the notifier factory).
load_dotenv()

from api_client import NWDPClient
from config import config
from data_store import DataStore
from insights import InsightInterpreter
from models.station import Station
from processing_engine import ProcessingEngine

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Page configuration
st.set_page_config(
    page_title="Groundwater Recharge Insight Dashboard",
    page_icon="💧",
    layout="wide",
    initial_sidebar_state="expanded"
)


def initialize_components():
    """Initialize application components."""
    if "data_store" not in st.session_state:
        st.session_state.data_store = DataStore()

    if "api_client" not in st.session_state:
        st.session_state.api_client = NWDPClient()

    if "processing_engine" not in st.session_state:
        st.session_state.processing_engine = ProcessingEngine()

    if "insight_interpreter" not in st.session_state:
        st.session_state.insight_interpreter = InsightInterpreter()


def main():
    """Main application entry point."""
    st.title("💧 Groundwater Recharge Insight Dashboard")
    st.markdown("**DWLR – NWDP Data Analysis**")

    # Initialize components
    initialize_components()

    # Sidebar
    with st.sidebar:
        st.header("Configuration")

        if config.is_mock_mode():
            st.error(
                "Data Mode: **MOCK**\n\n"
                "Readings are SYNTHETIC, generated by api_client. "
                "Unset DATA_MODE to return to real data."
            )
        elif config.is_api_mode():
            st.info("Data Mode: **API** — live NWDP fetch")
        else:
            st.success("Data Mode: **REAL (DB)**")
            st.caption(f"Source: {config.db_path}")

        st.caption(f"Trend window: {config.trend_window_days} days")

        notifier_name = os.getenv("NOTIFIER", "console").strip().lower()
        if notifier_name == "console":
            st.info("Notifier: **CONSOLE** (nothing is delivered)")
        else:
            st.warning(f"Notifier: **{notifier_name.upper()}** — messages go to real recipients")

        st.divider()
        page = st.radio(
            "Page",
            ["📊 Dashboard", "📝 Register Farmer", "👥 Farmers & Alerts"],
            label_visibility="collapsed",
        )

        if st.button("🔄 Refresh Data"):
            st.session_state.refresh_triggered = True

    if page == "📝 Register Farmer":
        render_register_farmer()
        return
    if page == "👥 Farmers & Alerts":
        render_farmers_and_alerts()
        return

    render_dashboard()


def render_dashboard():
    """Station analytics dashboard (the original view)."""
    data_store = st.session_state.data_store

    # Get stations
    stations = data_store.get_all_stations()

    # ------------------------------------------------------------------
    # NEW FIX: If stations table empty but readings exist, derive stations
    # ------------------------------------------------------------------
    if not stations:
        try:
            with data_store._get_connection() as conn:
                cursor = conn.cursor()
                cursor.execute("SELECT DISTINCT station_id FROM readings LIMIT 10")
                rows = cursor.fetchall()
                station_ids = [row["station_id"] for row in rows]

            if station_ids:
                stations = [
                    Station(
                        station_id=sid,
                        name=f"Station {sid}",
                        latitude=0,
                        longitude=0
                    )
                    for sid in station_ids
                ]
                st.info("Stations automatically derived from dataset readings.")

        except Exception:
            pass
    # ------------------------------------------------------------------

    if not stations:
        st.warning("No stations found. Run `python load_dataset.py` to ingest real readings from the CSV.")

        # Synthetic-data loading is opt-in only. Once mock readings are written to
        # the readings table they are indistinguishable from real ones on screen,
        # so this must never be reachable in the default (real) mode.
        if not config.is_mock_mode():
            st.info(
                "Synthetic sample data is disabled in real mode. To generate it "
                "deliberately, restart with DATA_MODE=mock."
            )
        elif st.button("Load Sample Stations (SYNTHETIC)"):
            with st.spinner("Loading sample stations and generating mock data..."):
                try:
                    api_client = st.session_state.api_client
                    data_store = st.session_state.data_store

                    mock_stations = api_client.fetch_stations()

                    if not mock_stations:
                        st.error("Failed to generate mock stations.")
                    else:
                        for station in mock_stations:
                            data_store.save_station(station)

                        st.success(f"Loaded {len(mock_stations)} stations.")

                        progress_bar = st.progress(0)
                        total_stations = len(mock_stations)

                        for idx, station in enumerate(mock_stations):

                            existing_readings = data_store.get_readings(station.station_id)
                            reading_count = len(existing_readings) if existing_readings else 0

                            if reading_count < 365:

                                end_date = datetime.now()
                                start_date = end_date - timedelta(days=365)

                                readings = api_client.fetch_readings(
                                    station.station_id,
                                    start_date,
                                    end_date
                                )

                                if readings:
                                    data_store.save_readings(readings)
                                    st.info(
                                        f"✅ Generated {len(readings)} readings for {station.name} "
                                        f"(had {reading_count} readings)"
                                    )
                                else:
                                    st.warning(f"⚠️ No readings generated for {station.name}")

                            else:
                                st.info(
                                    f"⏭️ Skipping {station.name} - {reading_count} readings already exist (>=365)"
                                )

                            progress_bar.progress((idx + 1) / total_stations)

                        st.success("✅ Sample data loading complete!")
                        st.rerun()

                except Exception as e:
                    st.error(f"Error loading sample data: {str(e)}")
                    logger.exception("Error in load sample stations")

    else:
        station_options = {f"{s.name} ({s.station_id})": s.station_id for s in stations}

        selected_station_name = st.selectbox(
            "Select Station",
            options=list(station_options.keys()),
            index=0
        )

        selected_station_id = station_options[selected_station_name]

        station = data_store.get_station(selected_station_id)

        if not station:
            station = Station(
                station_id=selected_station_id,
                name=f"Station {selected_station_id}",
                latitude=0,
                longitude=0
            )

        reference_date = data_store.get_max_reading_date(selected_station_id)

        if reference_date:
            logger.debug(
                f"Using reference_date={reference_date} for station {selected_station_id}"
            )

        display_station_summary(station, data_store)
        display_station_details(station, data_store, reference_date)


def display_station_summary(station: Station, data_store: DataStore):
    """Display summary card for selected station."""
    st.header(f"📊 {station.name}")

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("Station ID", station.station_id)

    with col2:
        if station.district:
            st.metric("District", station.district)

    with col3:
        if station.state:
            st.metric("State", station.state)

    with col4:
        metrics = data_store.get_latest_metrics(station.station_id)

        if metrics and metrics.risk_level:
            risk_color = {
                "Low Risk": "🟢",
                "Moderate Risk": "🟡",
                "High Risk": "🟠",
                "Critical Risk": "🔴"
            }.get(metrics.risk_level.value, "⚪")

            st.metric("Risk Level", f"{risk_color} {metrics.risk_level.value}")


def display_station_details(station: Station, data_store: DataStore, reference_date):
    """Display detailed analysis for selected station."""
    st.subheader("Detailed Analysis")

    if reference_date is None:
        st.warning(f"No readings found for station {station.station_id}")
        return

    end_date = reference_date
    start_date = end_date - timedelta(days=365)

    end_datetime = datetime.combine(end_date, datetime.max.time())
    start_datetime = datetime.combine(start_date, datetime.min.time())

    # Fix 3: Check for cached metrics first — only recalculate if none exist
    metrics = data_store.get_latest_metrics(station.station_id)

    if metrics is None:
        readings = data_store.get_readings(station.station_id)

        if not readings:
            st.warning(f"No readings found for station {station.station_id}")
            return

        processing_engine = st.session_state.processing_engine
        calculation_datetime = datetime.combine(reference_date, datetime.min.time())

        metrics = processing_engine.calculate_metrics(
            readings,
            calculation_date=calculation_datetime
        )

        # Save metrics so subsequent renders use the cache
        data_store.save_metrics(metrics)
    # else:
    #     st.caption("📦 Metrics loaded from cache.")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Trend Analysis")
        st.metric("Trend", metrics.trend_indicator.value)

        if metrics.trend_magnitude:
            st.metric("Change", f"{metrics.trend_magnitude:.2f} m")

    with col2:
        st.subheader("Risk Assessment")

        if metrics.risk_index is not None:
            st.metric("Risk Index", f"{metrics.risk_index:.1f}/100")

        if metrics.risk_level:
            st.metric("Risk Level", metrics.risk_level.value)

    insight_interpreter = st.session_state.insight_interpreter
    insight = insight_interpreter.generate_insight(metrics)

    st.subheader("📝 Interpretation")
    st.info(insight)

    st.subheader("Groundwater Level Chart")

    # Fetch all readings for chart (metrics window may be different)
    chart_readings = data_store.get_readings(station.station_id)

    if chart_readings:
        import plotly.graph_objects as go
        import numpy as np

        # Build dataframe for chart
        chart_df = pd.DataFrame([
            {"date": r.timestamp, "water_level_m": r.water_level_m}
            for r in chart_readings
        ]).sort_values("date")
        
        # Ensure y-axis has minimum 10m span to avoid exaggeration
        y_min = chart_df["water_level_m"].min()
        y_max = chart_df["water_level_m"].max()
        y_span = y_max - y_min
        if y_span < 10:
            padding = (10 - y_span) / 2
            y_range = [y_max + padding, y_min - padding]  # reversed
        else:
            y_range = [y_max + 1, y_min - 1]  # reversed, small padding

        # Determine chart color based on trend
        trend_colors = {
            "Recharging": "#2196F3",   # blue
            "Depleting":  "#F44336",   # red
            "Stable":     "#9E9E9E",   # grey
            "Insufficient Data": "#9E9E9E"
        }
        line_color = trend_colors.get(metrics.trend_indicator.value, "#9E9E9E")

        fig = go.Figure()

        # Actual readings line
        fig.add_trace(go.Scatter(
            x=chart_df["date"],
            y=chart_df["water_level_m"],
            mode="lines+markers",
            name="Water Level (m)",
            line=dict(color=line_color, width=2),
            marker=dict(size=4),
            hovertemplate="<b>%{x|%Y-%m-%d}</b><br>Water Level: %{y:.2f}m<extra></extra>"
        ))

        # Trend line overlay — always calculate directly from readings
        from scipy import stats as scipy_stats

        first_date = chart_df["date"].iloc[0]
        x_days = np.array([(d - first_date).days for d in chart_df["date"]])
        slope_result = scipy_stats.linregress(x_days, chart_df["water_level_m"].values)
        slope = slope_result.slope
        intercept = float(np.mean(chart_df["water_level_m"]) - slope * np.mean(x_days))
        trend_y = intercept + slope * x_days

        fig.add_trace(go.Scatter(
            x=chart_df["date"],
            y=trend_y,
            mode="lines",
            name="Trend Line",
            line=dict(color=line_color, width=2, dash="dash"),
            hovertemplate="<b>%{x|%Y-%m-%d}</b><br>Trend: %{y:.2f}m<extra></extra>"
        ))

        # Chart layout
        fig.update_layout(
            title=dict(
                text=f"{station.name} — Groundwater Level Over Time",
                font=dict(size=16)
            ),
            xaxis=dict(title="Date", showgrid=True, gridcolor="#333333"),
            yaxis=dict(
                title="Water Level (m below ground)",
                showgrid=True,
                gridcolor="#333333",
                range=y_range # Higher depth = lower on chart (more intuitive)
            ),
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
            hovermode="x unified",
            plot_bgcolor="#1e1e1e",
            paper_bgcolor="#1e1e1e",
            font=dict(color="#ffffff"),
            height=450
        )

        st.plotly_chart(fig, use_container_width=True)
    else:
        st.warning("No readings available for chart.")


# ==========================================================================
# ADVISORY MESSAGING PAGES
# ==========================================================================


def _messaging_store():
    """Lazily construct the messaging store, caching it in session state."""
    from messaging.store import MessagingStore

    if "messaging_store" not in st.session_state:
        st.session_state.messaging_store = MessagingStore()
    return st.session_state.messaging_store


def render_register_farmer():
    """Farmer registration, with a consent gate and the 25 km station rule."""
    from messaging.models import Language, PhoneError
    from messaging.store import (
        MAX_STATION_DISTANCE_KM,
        NoNearbyStationError,
        RegistrationError,
    )

    st.header("📝 Register Farmer")
    st.caption(
        "Farmers receive advisories on WhatsApp in their chosen language. "
        f"Registration requires a monitoring station within "
        f"{MAX_STATION_DISTANCE_KM:.0f} km — an advisory from further away "
        f"would not describe this farmer's groundwater."
    )

    store = _messaging_store()
    data_store = st.session_state.data_store
    stations = data_store.get_all_stations()

    if not stations:
        st.error("No stations loaded. Run `python load_dataset.py` first.")
        return

    with st.form("register_farmer", clear_on_submit=False):
        col1, col2 = st.columns(2)
        with col1:
            name = st.text_input("Farmer name *", placeholder="Balwinder Singh")
            village = st.text_input("Village *", placeholder="Longowal")
            phone = st.text_input(
                "Mobile number *",
                placeholder="9876543210",
                help="Accepts 9876543210, 09876543210, 919876543210 or +919876543210.",
            )
        with col2:
            district = st.text_input("District *", placeholder="Sangrur")
            language = st.selectbox(
                "Preferred language *",
                options=list(Language),
                format_func=lambda l: l.label,
            )
            registered_by = st.text_input("Registered by", placeholder="Field officer name")

        st.markdown("**Location** — used to assign the nearest monitoring station.")
        loc1, loc2 = st.columns(2)
        with loc1:
            latitude = st.number_input(
                "Latitude *", value=30.2000, min_value=6.0, max_value=38.0, format="%.4f"
            )
        with loc2:
            longitude = st.number_input(
                "Longitude *", value=75.8000, min_value=68.0, max_value=98.0, format="%.4f"
            )

        st.divider()
        consent = st.checkbox(
            "The farmer has given consent to receive groundwater advisory "
            "messages on this number.",
            value=False,
        )
        st.caption(
            "Consent is mandatory. Without it the farmer is not registered at all — "
            "there is no unconsented record."
        )

        submitted = st.form_submit_button("Register farmer", type="primary")

    if not submitted:
        return

    # Consent gate: block submission rather than storing an unconsented row.
    if not consent:
        st.error(
            "🚫 **Cannot register without consent.** Tick the consent checkbox. "
            "Consent is captured at registration or the farmer is not registered."
        )
        return

    missing = [
        label
        for label, value in (
            ("name", name), ("village", village), ("phone", phone), ("district", district),
        )
        if not str(value).strip()
    ]
    if missing:
        st.error(f"Please fill in the required field(s): {', '.join(missing)}.")
        return

    try:
        farmer = store.register_farmer(
            name=name,
            phone=phone,
            village=village,
            district=district,
            language=language,
            latitude=latitude,
            longitude=longitude,
            consent=True,
            registered_by=registered_by or None,
        )
    except NoNearbyStationError as exc:
        st.error(f"🚫 **Registration refused — no station within range**\n\n{exc}")
        nearest_id, nearest_km = store.find_nearest_station(latitude, longitude)
        if nearest_id:
            st.info(
                f"Nearest station is **{nearest_id}** at **{nearest_km:.1f} km** "
                f"(limit is {MAX_STATION_DISTANCE_KM:.0f} km)."
            )
        return
    except PhoneError as exc:
        st.error(f"🚫 **Invalid phone number**\n\n{exc}")
        return
    except RegistrationError as exc:
        st.error(f"🚫 **Could not register**\n\n{exc}")
        return
    except ValueError as exc:
        st.error(f"🚫 **Could not register**\n\n{exc}")
        return

    st.success(f"✅ Registered **{farmer.name}** (id {farmer.id})")
    m1, m2, m3 = st.columns(3)
    m1.metric("Assigned station", farmer.nearest_station_id)
    m2.metric("Distance", f"{farmer.distance_km:.1f} km")
    m3.metric("Language", farmer.language.label)
    st.caption(
        f"Stored number: {farmer.phone_masked}  ·  log id: {farmer.phone_hashed}  ·  "
        f"consent recorded {farmer.consent_ts}"
    )

    with st.expander("Preview the message this farmer would receive"):
        from messaging.composer import TemplateError, compose

        for band, reason in (
            ("CRITICAL", "DEFAULT"), ("WARNING", "DEFAULT"),
            ("WATCH", "DEFAULT"), ("NORMAL", "RECOVERED"),
        ):
            try:
                composed = compose(
                    band, reason, farmer.language,
                    {
                        "village": farmer.village,
                        "district": farmer.district,
                        "decline_m_per_year": "0.58",
                    },
                )
                st.markdown(f"**{band}** — `{composed.template_key}`")
                st.info(composed.text)
            except TemplateError as exc:
                st.warning(f"{band}: {exc}")


def render_farmers_and_alerts():
    """Operator view: registered farmers (masked) and full alert history."""
    from messaging.models import AlertStatus

    st.header("👥 Farmers & Alerts")
    store = _messaging_store()

    farmers = store.all_farmers(include_inactive=True)
    alerts = store.all_alerts(limit=500)

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Farmers", len(farmers))
    c2.metric("Active", sum(1 for f in farmers if f.active and f.consent))
    c3.metric("Alerts sent", sum(1 for a in alerts if a.status is AlertStatus.SENT))
    c4.metric("Suppressed", sum(1 for a in alerts if a.status is AlertStatus.SUPPRESSED))

    st.subheader("Registered farmers")
    if not farmers:
        st.info("No farmers registered yet. Use the Register Farmer page.")
    else:
        st.dataframe(
            pd.DataFrame([
                {
                    "id": f.id,
                    "name": f.name,
                    # Masked, never raw. The operator UI must not expose numbers.
                    "phone": f.phone_masked,
                    "village": f.village,
                    "district": f.district,
                    "lang": f.language.value,
                    "station": f.nearest_station_id,
                    "dist_km": round(f.distance_km, 1) if f.distance_km is not None else None,
                    "consent": "yes" if f.consent else "no",
                    "active": "yes" if f.active else "opted out",
                    "registered_by": f.registered_by or "—",
                }
                for f in farmers
            ]),
            use_container_width=True,
            hide_index=True,
        )
        st.caption(
            "Phone numbers are masked. Opted-out farmers are retained, never "
            "deleted, so the consent trail stays auditable."
        )

        active_ids = [f.id for f in farmers if f.active]
        if active_ids:
            with st.expander("Opt a farmer out"):
                target = st.selectbox("Farmer id", active_ids, key="optout_target")
                if st.button("Opt out", key="optout_btn"):
                    store.opt_out(target)
                    st.success(f"Farmer {target} opted out. Row retained for audit.")
                    st.rerun()

    st.subheader("Alert history")
    st.caption(
        "Suppressed rows are included deliberately — they show what the system "
        "chose NOT to send, which is as important as what it did send."
    )

    if not alerts:
        st.info(
            "No alerts yet. Try: `python -m messaging.dispatch --all --dry-run`, "
            "then run it without --dry-run to record sends."
        )
        return

    status_filter = st.multiselect(
        "Filter by status",
        options=[s.value for s in AlertStatus],
        default=[s.value for s in AlertStatus],
    )

    farmer_names = {f.id: f.name for f in farmers}
    rows = [
        {
            "id": a.id,
            "farmer": farmer_names.get(a.farmer_id, f"id {a.farmer_id}"),
            "station": a.station_id,
            "band": a.band,
            "reason_code": a.reason_code,
            "lang": a.language,
            "template_key": a.template_key,
            "status": a.status.value,
            "provider": a.provider or "—",
            "attempts": a.attempts,
            "created": a.created_ts,
            "message": a.message_text,
        }
        for a in alerts
        if a.status.value in status_filter
    ]
    if not rows:
        st.info("No alerts match the selected statuses.")
        return

    st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)

    st.subheader("Message detail")
    chosen = st.selectbox(
        "Alert id",
        [r["id"] for r in rows],
        format_func=lambda i: f"#{i} — {next(r['band'] for r in rows if r['id'] == i)}"
                              f" / {next(r['status'] for r in rows if r['id'] == i)}",
    )
    alert = next(a for a in alerts if a.id == chosen)
    badge = {
        AlertStatus.SENT: st.success,
        AlertStatus.SUPPRESSED: st.warning,
        AlertStatus.FAILED: st.error,
        AlertStatus.PENDING: st.info,
    }[alert.status]
    badge(f"**{alert.status.value.upper()}** · {alert.band} / {alert.reason_code} · "
          f"{alert.language} · `{alert.template_key}`")
    st.markdown("**Message text as delivered:**")
    st.info(alert.message_text)
    if alert.error:
        st.caption(f"Note: {alert.error}")
    if alert.provider_message_id:
        st.caption(f"Provider message id: {alert.provider_message_id}")


if __name__ == "__main__":
    main()